# To use:
#
#   $ micromamba env create -f environment.yml  # `conda` works too for this command
#   $ micromamba activate eindir-dev
#
name: eindir-dev
channels:
  - conda-forge
dependencies:
  - meson
  - cmake
  - ninja
  - pkg-config
  - openblas
  - python>=3.10
  - jupytext
  - jupyterlab
  - pdm
# Interactive
  - ipython
